QUESTIONS_JSON_PATH = "data/questions.json"
DEFAULT_NUMBER_OF_QUESTIONS = 10
LANGUAGE_SELECTION = False
TOPIC_SELECTION = True
QUESTION_NUMBER_SELECTION = False
CORRECT_ANSWER_WEIGHT = 1
WRONG_ANSWER_WEIGHT = 0.5
