services:
  - type: worker
    name: ssc-telegrambot
    runtime: python
    region: oregon
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    autoDeploy: true
    envVars:
      - key: TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.11
